[package]
name = "aqua-optics"
description = "Depth, medium, and transmission optics for Aqua shaders."
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
aqua-light.workspace = true
bevy = { workspace = true, features = ["bevy_asset"] }

[lints]
workspace = true
