[package]
name = "bevy-aqua-light"
description = "Incident and environment lighting primitives for Aqua shaders."
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
bevy = { workspace = true, features = ["bevy_asset", "bevy_shader"] }

[lints]
workspace = true
